version: "3.9"

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: ramzizarg/eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: ramzizarg/user-service:latest
    depends_on:
      - eureka-server
    networks:
      - backend

  reservation-service:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    image: ramzizarg/reservation-service:latest
    depends_on:
      - eureka-server
    networks:
      - backend

  workstation-service:
    build:
      context: ./workstation-service
      dockerfile: Dockerfile
    image: ramzizarg/workstation-service:latest
    depends_on:
      - eureka-server
    networks:
      - backend

  planning-service:
    build:
      context: ./planning-service
      dockerfile: Dockerfile
    image: ramzizarg/planning-service:latest
    depends_on:
      - eureka-server
    networks:
      - backend

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: ramzizarg/notification-service:latest
    depends_on:
      - eureka-server
    networks:
      - backend

  contact-service:
    build:
      context: ./contact-service
      dockerfile: Dockerfile
    image: ramzizarg/contact-service:latest
    depends_on:
      - eureka-server
    networks:
      - backend

  teletravail-service:
    build:
      context: ./teletravail-service
      dockerfile: Dockerfile
    image: ramzizarg/teletravail-service:latest
    depends_on:
      - eureka-server
    networks:
      - backend

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    image: ramzizarg/analytics-service:latest
    depends_on:
      - eureka-server
    networks:
      - backend

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
