version: '3.8'

services:
  backend:
    build: .
    container_name: backend-service
    image: ramzizarg/workstation:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
